# deploy-gcf.yml
name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Google Cloud Functions
      run: |
        dirs=(`ls`)
        for dir in $dirs;
        do
          echo ${dir:2}
        done
      working-directory: CloudFunctions
